// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh9exXwzruRgPuI8KtQkHqmGEjTRDy7Us',
    appId: '1:815538582382:web:9d943bf70972cf692e877f',
    messagingSenderId: '815538582382',
    projectId: 'audionyx-e0849',
    authDomain: 'audionyx-e0849.firebaseapp.com',
    storageBucket: 'audionyx-e0849.firebasestorage.app',
    measurementId: 'G-CP1WFJGZKJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw13OifRwjG8b2Rk2B8zYrbLs4seRhDp8',
    appId: '1:815538582382:android:7eff09131f8e019e2e877f',
    messagingSenderId: '815538582382',
    projectId: 'audionyx-e0849',
    storageBucket: 'audionyx-e0849.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3ewkekK1CkMGwf--67GjH-wp4b02mD8E',
    appId: '1:815538582382:ios:946f1574a2cfe4842e877f',
    messagingSenderId: '815538582382',
    projectId: 'audionyx-e0849',
    storageBucket: 'audionyx-e0849.firebasestorage.app',
    iosBundleId: 'com.example.audionyx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3ewkekK1CkMGwf--67GjH-wp4b02mD8E',
    appId: '1:815538582382:ios:946f1574a2cfe4842e877f',
    messagingSenderId: '815538582382',
    projectId: 'audionyx-e0849',
    storageBucket: 'audionyx-e0849.firebasestorage.app',
    iosBundleId: 'com.example.audionyx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh9exXwzruRgPuI8KtQkHqmGEjTRDy7Us',
    appId: '1:815538582382:web:8369b765d3a899c32e877f',
    messagingSenderId: '815538582382',
    projectId: 'audionyx-e0849',
    authDomain: 'audionyx-e0849.firebaseapp.com',
    storageBucket: 'audionyx-e0849.firebasestorage.app',
    measurementId: 'G-Y4EJLCZBVQ',
  );
}
